version: 0.2

env:
  parameter-store:
    GIT_USER: "git-user"
    GIT_PASS: "git-pass"
    CYPRESS_USERNAME: "cypress_username"
    CYPRESS_PASSWORD: "cypress_password"

phases:
  install:
    runtime-versions:
      python: 3.7
      nodejs: 10 
    commands:
      # Install dependencies needed for running tests
      - npm install
      - pip install --upgrade pip

      # Install sam (fixed version)
      - pip install pip==19.2.3 aws-sam-cli==1.15.0
      - pip install --upgrade awscli
     
  pre_build:
    commands:
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      # Execute Cypress tests
      - echo $PATH
      - npx cypress run
      - ./test.sh

  post_build:
    commands:
      # Post build commands
  
